# Generated by Django 2.2.10 on 2021-10-19 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=10000, verbose_name='Текст вопроса')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Text anwer needed'), (2, 'Choose one option'), (3, 'Choose many options')], default=1, verbose_name='Тип')),
                ('answer_options', models.CharField(db_index=True, max_length=10000, null=True, verbose_name='Варианты ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['survey'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(db_index=True, max_length=10000, verbose_name='Описание')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Survey_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='Пользователь')),
                ('answer', models.CharField(db_index=True, max_length=1000, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Question', verbose_name='Вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['survey'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Survey', verbose_name='Опрос'),
        ),
    ]
