# Generated by Django 3.2.8 on 2021-10-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_options',
            field=models.CharField(blank=True, db_index=True, max_length=10000, null=True, verbose_name='Варианты ответа'),
        ),
    ]
